name: Run Cypress and Allure

on: push

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Run Cypress tests
      run: npm test

    - name: Generate Allure report
      run: npm run allure:generate

    - name: Upload Allure report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report